### ISSUE TITLE
Writing UTF-8 error

### ISSUE THREAD

**Issue by nille02** [anqxyr/mkepub#17]
I got that Error if i try to write utf-8 pages/chapters

```
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\MyTests\make-epub.py", line 130, in <module>
    main()
  File "C:\Users\User\PycharmProjects\MyTests\make-epub.py", line 108, in main
    createEpub(novel, basePath, output)
  File "C:\Users\User\PycharmProjects\MyTests\make-epub.py", line 88, in createEpub
    book.add_page(title=chapter.name, content=chapter.content)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\mkepub\mkepub.py", line 96, in add_page
    self._write_page(page, content)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\mkepub\mkepub.py", line 157, in _write_page
    self._write(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\mkepub\mkepub.py", line 153, in _write
    file.write(env.get_template(template).render(**data))
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u016b' in position 10051: character maps to <undefined
```

My workaround was to change mkepub.py@L:152 
`        with open(str(self.path / path), 'w') as file:`
to
`        with open(str(self.path / path), 'w', encoding='utf-8') as file:`

**Comment by anqxyr** [comment]
Has been fixed already.

**Comment by nille02** [comment]
Then a Version bump might be useful, in the repository's are still the old version.
